'\" t
.\"     Title: glade-previewer
.\"    Author: Tristan Van Berkom Van Berkom <tristan.van.berkom@gmail.com>
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 03/27/2016
.\"    Manual: User Commands
.\"    Source: GNOME
.\"  Language: English
.\"
.TH "GLADE\-PREVIEWER" "1" "" "GNOME" "User Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
glade-previewer \- Preview glade user interface definitions
.SH "SYNOPSIS"
.HP \w'\fBglade\-previewer\ \fR\fB[OPTION...]\fR\ 'u
\fBglade\-previewer \fR\fB[OPTION...]\fR
.SH "DESCRIPTION"
.PP
\fBglade\-previewer\fR
is a tool that can load and display a User Interface that has been defined with glade\&. glade itself uses glade\-previewer, but it can also be used as a standalone utility\&.
.SH "OPTIONS"
.PP
The following options can be specified:
.PP
\fB\-f FILENAME\fR, \fB\-\-filename=FILENAME\fR
.RS 4
Name of the file to preview\&.
.RE
.PP
\fB\-t TOPLEVEL\fR, \fB\-\-toplevel=TOPLEVEL\fR
.RS 4
Name of the toplevel to preview\&.
.RE
.PP
\fB\-l\fR, \fB\-\-listen\fR
.RS 4
Listen on standard input\&.
.RE
.PP
\fB\-v\fR, \fB\-\-version\fR
.RS 4
Output version information and exit\&.
.RE
.PP
\fB\-\-display=DISPLAY\fR
.RS 4
X display to use\&.
.RE
.PP
One of the
\fB\-\-filename\fR
or
\fB\-\-listen\fR
options has to be specified\&.
.SH "SEE ALSO"
.PP
\fBglade\fR(1)
