'\" t
.\"     Title: glade
.\"    Author: Tristan Van Berkom Van Berkom <tristan.van.berkom@gmail.com>
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 03/27/2016
.\"    Manual: User Commands
.\"    Source: GNOME
.\"  Language: English
.\"
.TH "GLADE" "1" "" "GNOME" "User Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
glade \- Create GTK+ user interfaces
.SH "SYNOPSIS"
.HP \w'\fBglade\ \fR\fB[OPTION...]\fR\fB\ \fR\fB[FILE...]\fR\ 'u
\fBglade \fR\fB[OPTION...]\fR\fB \fR\fB[FILE...]\fR
.SH "DESCRIPTION"
.PP
\fBglade\fR
is a tool to create or edit user interfaces for GTK+ or GNOME applications\&. It saves the user interface descriptions in xml files which can be read by the GtkBuilder API that is part of GTK+\&.
.SH "OPTIONS"
.PP
The following options can be specified:
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Show help options\&.
.RE
.PP
\fB\-\-help\-all\fR
.RS 4
Show all help options\&.
.RE
.PP
\fB\-\-help\-debug\fR
.RS 4
Show Glade debug options\&.
.RE
.PP
\fB\-\-help\-gtk\fR
.RS 4
Show GTK+ options\&.
.RE
.PP
\fB\-\-version\fR
.RS 4
Output version information and exit\&.
.RE
.PP
\fB\-\-without\-devhelp\fR
.RS 4
Disable devhelp integration\&.
.RE
.PP
\fB\-\-display=DISPLAY\fR
.RS 4
X display to use\&.
.RE
.SH "SEE ALSO"
.PP
\fBdevhelp\fR(1)
